pipeline {
    agent any

    stages {
        stage('git checkout'){
            steps {
                git branch: 'main',
                url: 'https://github.com/vasanth129/terraform-practice.git'
            }
        }

        stage('Terraform Init'){
            steps {
                sh 'terraform init'
            }
        }

        stage('Terraform plan'){
            steps {
                sh 'terraform plan'
            }
        }

        stage('Terraform apply'){
            steps {
                sh 'terraform apply -auto-approve'
            }
        }

    }
}