pipeline {
    agent any

    stages {
        // stage('git checkout'){
        //     steps {
        //         git branch: 'main',
        //         url: 'https://github.com/vasanth129/terraform-practice.git'
        //     }
        // }

        stage('Terraform Init'){
            steps {
                dir ("day-2-tfvars"){
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform plan'){
            steps {
                dir ("day-2-tfvars"){
                    sh 'terraform plan'
                }
            }
        }

        stage('Terraform apply'){
            steps {
                dir ("day-2-tfvars"){
                    sh 'terraform apply -auto-approve'
                }
            }
        }

    }
}